# Generated by Django 6.0.6 on 2026-06-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('crashed', 'Crashed'), ('restarting', 'Restarting'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('uptime', models.PositiveBigIntegerField(default=0, help_text='seconds')),
                ('alerts_count', models.PositiveBigIntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_restart', models.DateTimeField(blank=True, null=True)),
                ('restart_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Engine statuses',
                'ordering': ['engine_name'],
            },
        ),
    ]
