# Generated by Django 6.0.6 on 2026-06-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('avg_requests_per_minute', models.FloatField(default=0)),
                ('avg_failed_auth_per_hour', models.FloatField(default=0)),
                ('avg_payload_length', models.FloatField(default=0)),
                ('common_ports', models.JSONField(default=list)),
                ('common_user_agents', models.JSONField(default=list)),
                ('common_endpoints', models.JSONField(default=list)),
                ('avg_packets_per_second', models.FloatField(default=0)),
                ('avg_bytes_per_second', models.FloatField(default=0)),
                ('observation_start', models.DateTimeField()),
                ('observation_end', models.DateTimeField(null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('sqli', 'SQL Injection'), ('xss', 'Cross-Site Scripting'), ('bruteforce', 'Brute Force'), ('dos', 'DoS/DDoS')], max_length=20)),
                ('version', models.IntegerField()),
                ('status', models.CharField(choices=[('training', 'Training'), ('active', 'Active'), ('archived', 'Archived'), ('failed', 'Failed')], default='training', max_length=20)),
                ('accuracy', models.FloatField(null=True)),
                ('f1_score', models.FloatField(null=True)),
                ('precision', models.FloatField(null=True)),
                ('recall', models.FloatField(null=True)),
                ('trained_at', models.DateTimeField(null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('model_path', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('attack_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('triggered_by', models.CharField(default='scheduler', max_length=50)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('duration_seconds', models.IntegerField(null=True)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('sqli', 'SQL Injection'), ('xss', 'Cross-Site Scripting'), ('bruteforce', 'Brute Force'), ('dos', 'DoS/DDoS')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('anomaly_score', models.FloatField(null=True)),
                ('src_ip', models.GenericIPAddressField(null=True)),
                ('dst_ip', models.GenericIPAddressField(null=True)),
                ('src_port', models.IntegerField(null=True)),
                ('dst_port', models.IntegerField(null=True)),
                ('payload_sample', models.TextField(blank=True)),
                ('features_triggered', models.JSONField(default=list)),
                ('verdict', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed Threat'), ('false_positive', 'False Positive')], default='pending', max_length=20)),
                ('verdict_at', models.DateTimeField(null=True)),
                ('raw_features', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('linked_threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_detections', to='threats.threat')),
                ('model_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.mlmodel')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['attack_type', '-detected_at'], name='intelligenc_attack__73dbb2_idx'), models.Index(fields=['verdict', '-detected_at'], name='intelligenc_verdict_630b66_idx')],
            },
        ),
    ]
