# Generated by Django 6.0.6 on 2026-06-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('os_detected', models.CharField(blank=True, max_length=255)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('vulnerabilities', models.JSONField(blank=True, default=list)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-risk_score', 'ip_address'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('discovery', 'Host Discovery'), ('port', 'Port Scan'), ('os', 'OS Fingerprint'), ('vuln', 'Vulnerability Scan'), ('service', 'Service Version'), ('stealth', 'Stealth Scan'), ('udp', 'UDP Scan'), ('arp', 'ARP Scan')], max_length=16)),
                ('target', models.CharField(help_text="CIDR, IP, or 'localnet'", max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Completed'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('findings', models.JSONField(blank=True, default=dict)),
                ('host_count', models.PositiveIntegerField(default=0)),
                ('vulnerability_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
