# Generated by Django 6.0.6 on 2026-06-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the alert fired')),
                ('engine', models.CharField(choices=[('suricata', 'Suricata'), ('snort', 'Snort 3')], db_index=True, max_length=16)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], db_index=True, max_length=8)),
                ('category', models.CharField(blank=True, db_index=True, max_length=128)),
                ('src_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('src_port', models.PositiveIntegerField(blank=True, null=True)),
                ('dst_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=16)),
                ('signature', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('raw_alert', models.JSONField(blank=True, default=dict)),
                ('advice', models.TextField(blank=True, help_text='AI/rule-based remediation advice')),
                ('is_blocked', models.BooleanField(default=False)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['severity', '-timestamp'], name='threats_thr_severit_af1f45_idx'), models.Index(fields=['src_ip', '-timestamp'], name='threats_thr_src_ip_62eaba_idx')],
            },
        ),
    ]
